mode: 'rule'
ipv6: true
bind-address: "*"
geodata-mode: true
geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb"
  asn: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-asn.mmdb"
geo-auto-update: true
geo-update-interval: 24
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: 'gvisor'
  dns-hijack:   
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
sniffer:
  enable: false
clash-for-android: 
  append-system-dns: true
  ui-subtitle-pattern: ""
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  listen: '0.0.0.0:5335'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter-mode: 'blacklist'
  fake-ip-filter:
    - 'geosite:connectivity-check'
    - 'geosite:private'
  default-nameserver:
    - system
    - 223.5.5.5
    - 114.114.114.114
    - 180.184.1.1
    - 119.29.29.29
    - 180.76.76.76
  fallback: null
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - "tls://dot.pub"
    - "tls://dns.alidns.com"
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - "tls://dot.pub"
    - "tls://dns.alidns.com"
  direct-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 180.184.1.1
    - 119.29.29.29
    - 180.76.76.76
  direct-nameserver-follow-policy: true
  nameserver-policy:
    "domain-suffix:software.tongji.edu.cn":
      - 202.120.190.208
      - 202.120.190.108
      - 202.96.209.5
    "domain-suffix:linux.do": 
      - 'https://hellowayel.ddd.oaifree.com/query-dns'
      - 'https://doh.pub/dns-query'
      - 'https://dns.alidns.com/dns-query'
      - "tls://dot.pub"
      - "tls://dns.alidns.com"
    "geosite:cn":
      - system
      - 223.5.5.5
      - 114.114.114.114
      - 180.184.1.1
      - 119.29.29.29
      - 180.76.76.76
    "geosite:steam@cn":
      - system
      - 223.5.5.5
      - 114.114.114.114
      - 180.184.1.1
      - 119.29.29.29
      - 180.76.76.76
    "geosite:category-games@cn":
      - system
      - 223.5.5.5
      - 114.114.114.114
      - 180.184.1.1
      - 119.29.29.29
      - 180.76.76.76
    "geosite:gfw":
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
